name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, devin/1753289491-phase1-foundation-risk-mitigation ]
  pull_request:
    branches: [ main, devin/1753289491-phase1-foundation-risk-mitigation ]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: npm audit --audit-level=moderate
      - run: npm run lint || true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: npm test || echo "No tests configured yet"

  build-android:
    runs-on: ubuntu-latest
    needs: [security-audit, test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: npm install
      - run: npm run build
      - run: npx cap sync android
      - run: npx cap build android
      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          files: android/app/build/outputs/apk/debug/app-debug.apk
          generate_release_notes: true

  build-ios:
    runs-on: macos-latest
    needs: [security-audit, test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
      - run: npx cap sync ios
      - run: npx cap build ios
      - name: Upload iOS App
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: ios/App/build/Build/Products/Debug-iphoneos/App.app
          retention-days: 30

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
